image: bahmutov/cypress-image
# caching node_modules folder
# https://about.gitlab.com/2016/03/01/gitlab-runner-with-docker/
cache:
  paths:
  - node_modules/
stages:
  - build
  - test
build-specs:
  stage: build
  script:
    - npm install
    - npm test
    - npm run build
  artifacts:
    paths:
      - cypress/integration

      
# Hidden job that defines an anchor named 'e2e_test_definition'
# This job will be automatically assigned "test" phase
.job_template: &e2e_test_definition
  script:
    - cypress ci --spec "cypress/integration/$CI_BUILD_NAME.js"
# as many job definitions as spec files
# runs cypress ci --spec cypress/integration/one_spec.js
one_spec:
  <<: *e2e_test_definition
# runs cypress ci --spec cypress/integration/two_spec.js
two_spec:
  <<: *e2e_test_definition